version: '3.7'

services:
  vsftpd:
    image: akue/vsftpd
    env_file:
      - .env
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - data:/home/vsftpd
      - ./logs:/var/log/vsftpd
      - ./ui/certbot/conf/live/vsftpd:/etc/vsftpd/cert/
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  django_gunicorn:
    volumes:
      - static:/static
      - data:/data
    env_file:
      - .env
    build: djangoApp
    expose:
      - 80
    depends_on:
      - db
  nginx:
    restart: unless-stopped
    volumes:
      - static:/static
      - ./ui/certbot/conf:/etc/letsencrypt
      - ./ui/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ui
      args:
        ENV: ${ENV}
        SERVER_ADDRESS: ${SERVER_ADDRESS}
        NGINX_MODE: ${NGINX_MODE}
    env_file:
      - .env
    depends_on:
      - django_gunicorn
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./ui/certbot/conf:/etc/letsencrypt
      - ./ui/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static:
  postgres-data:
  data:
