version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build: djangoApp
    expose:
      - "80"
  nginx:
    volumes:
      - static:/static
    ports:
      - "80:80"
    build: ui
    depends_on:
      - django_gunicorn

volumes:
  static:
  html: