/* eslint-disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;
const nginx_mode = argv.nginx_mode;

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

// Checks whether command line argument of `prod` was provided signifying production mode
const isProduction = environment === 'prod';
const isSSL = nginx_mode != 'dev';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

const http_or_https = isSSL
  ? 'https'
  : 'http';

//creates the `environment.prod.ts` or `environment.ts` file if it does not exist
writeFileUsingFS(targetPath, '');

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production:  ${isProduction},
    staticURL: '',
    apiUrl: "${http_or_https}://${argv.server_address}"
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* eslint-enable */
